### ISSUE TITLE
cartpole example does not run

### ISSUE THREAD

**Issue by jpiabrantes** [EMI-Group/tensorneat#5]
The error comes from line 528 on the species/default.py.

```python
node_attr_func = jax.vmap(genome.node_gene.new_random_attrs, in_axes=(None,0))
input_attrs = node_attr_func(input_keys)
output_attrs = node_attr_func(output_keys)
```

error `ValueError: vmap in_axes must be an int, None, or a tuple of entries corresponding to the positional arguments passed to the function, but got len(in_axes)=2, len(args)=1`

This error can be fixed by removing the None from in_axes
```python
node_attr_func = jax.vmap(genome.node_gene.new_random_attrs, in_axes=(None,0))
```

But then another error is raised and I gave up.

**Comment by WLS2002** [comment]
Thank you very much for using the tensorneat library!

The issue you mentioned does indeed exist on our main branch due to some untested changes that were made previously. We are currently primarily maintaining the **remove_enable** branch (which I have just set as the default branch). All examples in this branch are functional, and it includes many new features. **Please switch to the remove_enable branch, where the cartpole example runs correctly.**

I apologize for the inconvenience. Our recent focus has been on developing new features, and we have neglected the maintenance of the GitHub repository. We are planning to release tensorneat 0.1.0 soon, which will include thoroughly checked code along with related documentation and usage tutorials.

Thank you again for your attention to the tensorneat library!
