### ISSUE TITLE
Explicit fitness sharing vs linear ranking selection

### ISSUE THREAD

**Issue by sopotc** [EMI-Group/tensorneat#8]
From reading the [code](https://github.com/EMI-Group/tensorneat/blob/220e7ec9504d84c07a3f71a3e7efaf0dffc9af2e/src/tensorneat/algorithm/neat/species.py#L237), it appears that the way that the speciate function is done in the neat algorithm is by assigning offsprings based on the linear ranking selection of species. 

However, in my understanding of the NEAT paper, explicit fitness sharing is used to distribute offspring reproduction among species. Thus, the reproduction opportunities for species are proportional to their _adjusted fitness_, rather than to the _rank_ of their fitness. This is an important distinction, as it could project considerable smoothing and impact performance.

I'm curious if you did any ablation, or whether something specific motivated you to move away from explicit fitness sharing.

**Comment by WLS2002** [comment]
Thank you very much for your reminder, and I sincerely apologize for noticing this issue a month later. This is indeed a flaw in the implementation of TensorNEAT.

The previous implementation used an approach called **rank-based fitness shaping**, which helps mitigate the impact of outliers (extremely high or low fitness values) or significant differences in fitness scales on the algorithm. This strategy is widely used in Evolution Strategies (e.g., CMA-ES) algorithms.

Experimental results with TensorNEAT show that rank-based fitness shaping can also be applied to NEAT. However, it is indeed inconsistent with the original NEAT approach mentioned in the paper. **Therefore, I have now added a method to adjust fitness based on species rather than ranks when calculating the fitness of species members.** Users can choose the method by specifying `species_number_calculate_by` in the NEAT configuration.

Thank you again for your reminder and for your interest in TensorNEAT! If you have further questions or suggestions for improving TensorNEAT, I’d be more than happy to follow up.
