### ISSUE TITLE
Making non-recurrent HyperNEAT policies

### ISSUE THREAD

**Issue by eleninisioti** [EMI-Group/tensorneat#9]
Hello, this is related to another question I posted [here](https://github.com/EMI-Group/evox/discussions/155). First, thanks a lot for your quick and clear reply, things make sense! I just have a couple of follow-up questions to make sure I understood.

If I would like to implement HyperNEAT disallowing recurrent connections, I can define another substrate where I set the query_coors appropriately (without the cartesian product). Can I then still use the RecurrentGenome or should I use the DefaultGenome? My intuition is that I can still use the RecurrentGenome and the instantiated policy will be feedforward because it will be only queried for the feedforward connections. As I said in the other post I am not sure if using DefaultGenome in HyperNEAT will result in erratic behaviour.

I also see that you recently added a method for visualizing networks of DefaultGenome, that's great! I imagine it is not possible to visualize a RecurrentGenome? But perhaps I could visualize the RecurrentGenome  if it leads to a feedforward network (if I use the substrate I described above?) 

Then an observation/question about the provided example of [HyperNEAT solving the XOR task](https://github.com/EMI-Group/tensorneat/blob/main/examples/func_fit/xor_hyperneat.py). If I understand correctly, the episode consists of eight steps where at each step the policy receives an observation of the 3 input bits and that in each episode the order of the vectors is fixed . My impression is that using a recurrent policy here is wrong because it can memorize the order of output bits instead of fitting the desired function.

**Comment by WLS2002** [comment]
Hello, 

I have implemented HyperNEAT with a feedforward substrate ([`MLPSubstrate`](https://github.com/EMI-Group/tensorneat/blob/main/src/tensorneat/algorithm/hyperneat/substrate/mlp.py)) and a feedforward genome ([`DefaultGenome`](https://github.com/EMI-Group/tensorneat/blob/main/src/tensorneat/algorithm/hyperneat/hyperneat_feedforward.py)). You can find a usage example [here](https://github.com/EMI-Group/tensorneat/blob/main/examples/func_fit/xor_hyperneat_feedforward.py). 

Regarding your questions:

1. **Using `RecurrentGenome` with a feedforward substrate:**  
   Yes, you can use `RecurrentGenome` with a feedforward substrate. There is no difference in the outputs when using either `DefaultGenome` or `RecurrentGenome` on a feedforward substrate. However, `DefaultGenome` is significantly faster, so it might be the better choice in terms of performance.  

2. **Visualizing `RecurrentGenome`:**  
   At present, I don’t have a method to visualize a `RecurrentGenome` due to the cyclic connections in its network. To address this, I implemented HyperNEAT with `FeedforwardGenome` instead, and the visualization of both the CPPN network and the HyperNEAT network is included in the [example](https://github.com/EMI-Group/tensorneat/blob/main/examples/func_fit/xor_hyperneat_feedforward.py). You can use it as a reference to implement your own substrate and HyperNEAT design.

Thank you again for your interest in TensorNEAT! If you have any further questions, feel free to post them here.
